Array Creation
 Create a 1D NumPy array with elements ranging from 0 to 9.
 Create a 3x3 NumPy array filled with the value 7.

In [46]:
import numpy as np
array=np.arange(10)
print(array)
array2=np.full((3,3),7)
print(array2)


[0 1 2 3 4 5 6 7 8 9]
[[7 7 7]
 [7 7 7]
 [7 7 7]]


Array Operations
 Create two 2D arrays of shape (3, 3) and perform element-wise addition and
multiplication.
 Create a 4x4 array of random integers between 10 and 50. Find the maximum and
minimum values in the array.

In [48]:
arr=np.arange(9).reshape(3,3)
print(arr)
arr2=np.arange(9).reshape(3,3)
print(arr2)
arr3=arr+arr2
print(arr3)
arr4=arr*arr2
print(arr4)
arr5=np.random.randint(10,50,size=(4,4))
print(arr5)
print(arr5.max())
print(arr5.min())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]
[[11 32 17 14]
 [32 33 32 32]
 [32 17 30 16]
 [13 39 44 17]]
44
11


Indexing and Slicing
 Create a 5x5 array of sequential numbers starting from 1. Extract the middle 3x3 sub-
array.
 Given a 2D array of shape (4, 4), set all elements in the first row to 0.

In [49]:
arr=np.arange(1,26).reshape(5,5)
print(arr)
arr2=arr[1:4,1:4]
print(arr2)
arr3=np.zeros((4,4))
print(arr3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Mathematical Operations
 Compute the mean, median, and standard deviation of a randomly generated array of
1000 elements.
 Perform a dot product of two 1D arrays of length 4.

In [53]:
arr=np.random.rand(1000)
print(arr)
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
arr1=np.random.rand(4)

arr2=np.random.rand(4)

arr3=np.dot(arr1,arr2)
print(arr3)

[0.08996952 0.58417878 0.17975348 0.45714667 0.60146511 0.19334145
 0.8318638  0.98962855 0.05746138 0.74114873 0.60997423 0.35992734
 0.15505329 0.87195948 0.27010937 0.18596728 0.7305621  0.92970069
 0.38544331 0.67971553 0.30927188 0.88178225 0.6612356  0.40565531
 0.87091996 0.5972106  0.74229041 0.90811628 0.05329088 0.78004219
 0.94871018 0.37304185 0.89599187 0.62683607 0.14967348 0.70655309
 0.72592807 0.04682184 0.45487015 0.62040866 0.21515106 0.69448169
 0.52786829 0.69972451 0.72502901 0.86407276 0.3098497  0.28343698
 0.5524722  0.59435595 0.93607266 0.29032231 0.01359303 0.62446659
 0.4896916  0.02487437 0.02382959 0.96524692 0.26891807 0.98614252
 0.05463734 0.70376736 0.62953538 0.94176527 0.66910641 0.27086313
 0.04330585 0.21607016 0.88024175 0.36550779 0.05442808 0.07657088
 0.35170826 0.58112254 0.29787116 0.44508099 0.74766862 0.81340379
 0.08740615 0.23879503 0.28223491 0.87562283 0.15463953 0.82002282
 0.09247605 0.52630332 0.05271282 0.25973145 0.30837773 0.1282

Broadcasting
 Create a 5x5 array of zeros and add a 1D array of shape (5,) to each row of the 2D array
using broadcasting.
 Create a 3x3 array and subtract a scalar value from it.

In [55]:
arr=np.zeros((5,5))
print(arr)
arr2=np.arange(5)
print(arr2)
arr3=arr+arr2
print(arr3)
arr4=np.arange(9).reshape(3,3)
print(arr4)
arr5=arr4-1
print(arr5)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[0 1 2 3 4]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]


Aggregations
 Calculate the sum of all elements in a 6x6 array with random values between 1 and 10.
 Find the index of the maximum value in a 1D array of 50 random values.

In [60]:
arr=np.random.randint(1,10,size=(6,6))
print(arr)
print(np.sum(arr))
arr2= np.random.randint(0, 100, size=50)

print(arr2)
print(np.argmax(arr2))


[[6 7 6 8 4 9]
 [4 5 5 9 7 8]
 [4 8 2 5 3 9]
 [9 6 3 6 6 5]
 [9 9 5 1 7 9]
 [6 3 5 2 8 2]]
210
[25 56 30 39 85 81 20 70 85  1 66 47 63 18 18 72 32 89 89 54  0  7 96 66
  2 10 10  5 56 10 12 89 11 73 41  6 71 85 85 52 41 35  9 36 85 41 22 38
 48 32]
22


Reshaping and Flattening
 Reshape a 1D array of 12 elements into a 3x4 array.
 Flatten a 4x4 array into a 1D array.

In [64]:
array1D=np.arange(12)
print(array1D)
arr2=array1D.reshape(3,4)
print(arr2)
arr3=np.arange(16).reshape(4,4)
print(arr3)
arr4=arr3.flatten()
print(arr4)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


Linear Algebra
 Solve a system of linear equations represented by a 2x2 matrix and a 2x1 vector.
 Compute the inverse of a 3x3 matrix (if it is invertible).

In [67]:
arr=np.array([[2,3],[4,5]])
print(arr)
arr2=np.array([[1],[2]])
print(arr2)
arr3=np.linalg.solve(arr,arr2)
print(arr3)
arr4=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr4)


#inverse not possible

[[2 3]
 [4 5]]
[[1]
 [2]]
[[0.5]
 [0. ]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Statistical Analysis

 Create a 100x100 array of random numbers and calculate the correlation coefficient
matrix.
 Compute the cumulative sum of a 1D array of 20 elements.

In [69]:
arr=np.random.rand(100,100)
print(arr)
print(np.corrcoef(arr))
arr2=np.random.rand(20)
print(arr2)
print(np.cumsum(arr2))


[[0.21646071 0.47374951 0.36721486 ... 0.27079727 0.71956316 0.84729669]
 [0.32798053 0.87913192 0.65081192 ... 0.75254002 0.91555591 0.33922931]
 [0.4124503  0.66523354 0.05752767 ... 0.27444314 0.63643047 0.23740441]
 ...
 [0.24555162 0.05487775 0.24370625 ... 0.7668042  0.47055637 0.4052137 ]
 [0.33101725 0.87810069 0.29059756 ... 0.57912436 0.44583178 0.45997779]
 [0.49297851 0.24483249 0.70581677 ... 0.08913579 0.52199612 0.45518562]]
[[ 1.          0.13901547 -0.0633388  ... -0.07862138  0.12485823
   0.14205537]
 [ 0.13901547  1.          0.09586694 ...  0.2095227  -0.06207559
   0.08006741]
 [-0.0633388   0.09586694  1.         ... -0.097732   -0.0406357
  -0.09856104]
 ...
 [-0.07862138  0.2095227  -0.097732   ...  1.         -0.08493011
  -0.00218816]
 [ 0.12485823 -0.06207559 -0.0406357  ... -0.08493011  1.
   0.0296763 ]
 [ 0.14205537  0.08006741 -0.09856104 ... -0.00218816  0.0296763
   1.        ]]
[0.35351877 0.82969827 0.58562371 0.18314161 0.98426102 0.1253452
 0.05712

Advanced Indexing
 Create a 4x4 matrix and use boolean indexing to set all elements greater than 5 to -1.
 Generate a 2D array of shape (5, 5) and use advanced indexing to extract specific rows
and columns based on conditions.

In [72]:
import numpy as np

# Step 1
arr = np.arange(16).reshape(4, 4)
print("Original arr:")
print(arr)

# Step 2
arr[arr > 5] = -1
print("Modified arr:")
print(arr)

# Step 3
arr2 = np.arange(25).reshape(5, 5)
print("arr2:")
print(arr2)

# Step 4
# Correcting the if statement
if (arr2[1:] > 5).any():
    print("Sub-array where elements are greater than 5:")
    print(arr2[1:])
else:
    print("no")


Original arr:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Modified arr:
[[ 0  1  2  3]
 [ 4  5 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]
arr2:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Sub-array where elements are greater than 5:
[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
